[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node build/index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

# Environment variables needed for production
[build.environment]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=1024"
NODE_VERSION = "20"

# Required environment variables that must be set in Railway dashboard
[deploy.environment]
NODE_ENV = "production"
# DEEPGRAM_API_KEY - REQUIRED: Get from https://console.deepgram.com/ and set in Railway Variables
DEEPGRAM_API_KEY = "your_deepgram_api_key_here"  # ⚠️ REPLACE THIS WITH YOUR ACTUAL KEY IN RAILWAY DASHBOARD!
# DEEPL_API_KEY - OPTIONAL: For translations, get from https://www.deepl.com/pro-api
DEEPL_API_KEY = ""
PORT = "3000"
HOST = "0.0.0.0"

# Build cache configuration
[build.cache]
directories = ["node_modules"]
