[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node build/index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

# Simplified Build Configuration
[build.environment]
NODE_ENV = "production"

# Production Environment - Keep Only Essentials
[deploy.environment]
NODE_ENV = "production"
PORT = "$PORT"  # Railway sets this automatically
HOST = "0.0.0.0"

# REQUIRED API KEY - Must be set in Railway Variables
# DEEPGRAM_API_KEY must be set in Railway Dashboard > Variables

# Optional Environment Variables (set in Railway if needed)
# DEEPL_API_KEY (for translation features)
# GEMINI_API_KEY (fallback AI)
# ADMIN_PASSWORD (for admin access)
