[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node build/index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

# Environment variables needed for production
[build.environment]
NODE_ENV = "production"
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"

# Required environment variables that must be set in Railway dashboard
[deploy.environment]
NODE_ENV = "production"
# DEEPGRAM_API_KEY - REQUIRED: Get from https://console.deepgram.com/ and set in Railway Variables
# ⚠️ ADD YOUR KEY: Set DEEPGRAM_API_KEY in Railway Dashboard Variables section
# Example: DEEPGRAM_API_KEY: dg_your_real_key_here
PORT = "3000"
HOST = "0.0.0.0"

# PERFORMANCE OPTIMIZATIONS FOR REAL-TIME VOICE CALLS
NODE_OPTIONS = "--max-old-space-size=4096"         # 4GB memory for voice processing
WEBSOCKET_TIMEOUT = "600000"                       # 10 minutes sustained connections
WEBSOCKET_MAX_CONNECTIONS = "50"                   # Individual learners optimized
AUDIO_BUFFER_SIZE = "10240"                        # Smooth audio streaming buffers
CONNECTION_POOL_SIZE = "5"                         # HTTP connection pooling
VOICE_SESSION_TIMEOUT = "900000"                   # 15 minute voice practice
AUDIO_QUALITY = "high"                             # Professional German synthesis

# Build cache configuration - optimizes subsequent deployments
[build.cache]
directories = ["node_modules"]
